//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bieb.Web.Resources.BookStrings", typeof(BookStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back cover.
        /// </summary>
        public static string CoverBackAlt {
            get {
                return ResourceManager.GetString("CoverBackAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to front cover.
        /// </summary>
        public static string CoverFrontAlt {
            get {
                return ResourceManager.GetString("CoverFrontAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string Editors {
            get {
                return ResourceManager.GetString("Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find this book on.
        /// </summary>
        public static string FindBookOn {
            get {
                return ResourceManager.GetString("FindBookOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see if we can find anything on Goodreads, a book-review site:.
        /// </summary>
        public static string GoodReadsDescription {
            get {
                return ResourceManager.GetString("GoodReadsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodreads Reviews.
        /// </summary>
        public static string GoodReadsReviews {
            get {
                return ResourceManager.GetString("GoodReadsReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book cover icon.
        /// </summary>
        public static string IconAlt {
            get {
                return ResourceManager.GetString("IconAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are all the novels (books with a single main story), anthologies (collected stories by different authors), and collections (collected stories from a single author) that are, have been, or should be in my library..
        /// </summary>
        public static string IndexIntroduction {
            get {
                return ResourceManager.GetString("IndexIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string Isbn {
            get {
                return ResourceManager.GetString("Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN Language ID.
        /// </summary>
        public static string IsbnLanguage {
            get {
                return ResourceManager.GetString("IsbnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string IsbnLanguagePlaceholder {
            get {
                return ResourceManager.GetString("IsbnLanguagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 978-1-12-123456-1.
        /// </summary>
        public static string IsbnPlaceholder {
            get {
                return ResourceManager.GetString("IsbnPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LibraryStatus {
            get {
                return ResourceManager.GetString("LibraryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no books in the database yet..
        /// </summary>
        public static string NoBooksInDatabase {
            get {
                return ResourceManager.GetString("NoBooksInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author / Editor.
        /// </summary>
        public static string PeopleInvolved {
            get {
                return ResourceManager.GetString("PeopleInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published By.
        /// </summary>
        public static string PublishedBy {
            get {
                return ResourceManager.GetString("PublishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string ReviewText {
            get {
                return ResourceManager.GetString("ReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something interesting about this book; your opinion, an anecdote, etc..
        /// </summary>
        public static string ReviewTextPlaceholder {
            get {
                return ResourceManager.GetString("ReviewTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        public static string Stories {
            get {
                return ResourceManager.GetString("Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a subtitle.
        /// </summary>
        public static string SubtitlePlaceholder {
            get {
                return ResourceManager.GetString("SubtitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title.
        /// </summary>
        public static string TitlePlaceholder {
            get {
                return ResourceManager.GetString("TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        public static string Translators {
            get {
                return ResourceManager.GetString("Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeHeader {
            get {
                return ResourceManager.GetString("TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was recently added to my library.
        /// </summary>
        public static string WasRecentlyAdded {
            get {
                return ResourceManager.GetString("WasRecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to written by.
        /// </summary>
        public static string WrittenBy {
            get {
                return ResourceManager.GetString("WrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string YearHeader {
            get {
                return ResourceManager.GetString("YearHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1984.
        /// </summary>
        public static string YearPlaceholder {
            get {
                return ResourceManager.GetString("YearPlaceholder", resourceCulture);
            }
        }
    }
}
