//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bieb.Web.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string Gender0 {
            get {
                return ResourceManager.GetString("Gender0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♂.
        /// </summary>
        public static string Gender1 {
            get {
                return ResourceManager.GetString("Gender1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♀.
        /// </summary>
        public static string Gender2 {
            get {
                return ResourceManager.GetString("Gender2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♂/♀.
        /// </summary>
        public static string Gender3 {
            get {
                return ResourceManager.GetString("Gender3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just for reference.
        /// </summary>
        public static string LibraryStatus0 {
            get {
                return ResourceManager.GetString("LibraryStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have it!.
        /// </summary>
        public static string LibraryStatus1 {
            get {
                return ResourceManager.GetString("LibraryStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarded.
        /// </summary>
        public static string LibraryStatus2 {
            get {
                return ResourceManager.GetString("LibraryStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want it!.
        /// </summary>
        public static string LibraryStatus3 {
            get {
                return ResourceManager.GetString("LibraryStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Role0 {
            get {
                return ResourceManager.GetString("Role0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string Role1 {
            get {
                return ResourceManager.GetString("Role1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Role2 {
            get {
                return ResourceManager.GetString("Role2", resourceCulture);
            }
        }
    }
}
