//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bieb.Web.Resources.HomeStrings", typeof(HomeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authored stories in.
        /// </summary>
        public static string AuthoredStoriesIn {
            get {
                return ResourceManager.GetString("AuthoredStoriesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse all books in my library: novels, anthologies, and collections..
        /// </summary>
        public static string BrowseBooks {
            get {
                return ResourceManager.GetString("BrowseBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read on....
        /// </summary>
        public static string BrowseBooksLink {
            get {
                return ResourceManager.GetString("BrowseBooksLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the folks behind the books: authors, editors, and translators..
        /// </summary>
        public static string BrowsePeople {
            get {
                return ResourceManager.GetString("BrowsePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a look....
        /// </summary>
        public static string BrowsePeopleLink {
            get {
                return ResourceManager.GetString("BrowsePeopleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to different books in my library.
        /// </summary>
        public static string DifferentBooks {
            get {
                return ResourceManager.GetString("DifferentBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library is Empty!.
        /// </summary>
        public static string EmptyDatabase {
            get {
                return ResourceManager.GetString("EmptyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh noes! The entire library is empty. No books, no authors, not even a bit of tumbleweed. You&apos;ll need some data before the site will be up to speed!.
        /// </summary>
        public static string EmptyDatabaseExplanation {
            get {
                return ResourceManager.GetString("EmptyDatabaseExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy!.
        /// </summary>
        public static string Enjoy {
            get {
                return ResourceManager.GetString("Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse related info on authors, editors, translators, publishers, series and short stories..
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore The Content.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t know where to start? Let the site surprise you with a book or author..
        /// </summary>
        public static string GetSurprised {
            get {
                return ResourceManager.GetString("GetSurprised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of a library.
        /// </summary>
        public static string HomeImageAlt {
            get {
                return ResourceManager.GetString("HomeImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all books that were, are, and should be in my personal library..
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added.
        /// </summary>
        public static string RecentlyAdded {
            get {
                return ResourceManager.GetString("RecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise me!.
        /// </summary>
        public static string SurpriseLink {
            get {
                return ResourceManager.GetString("SurpriseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse my Library!.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Birth Dates.
        /// </summary>
        public static string TodaysBirthDates {
            get {
                return ResourceManager.GetString("TodaysBirthDates", resourceCulture);
            }
        }
    }
}
