//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IsbnLanguagesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IsbnLanguagesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bieb.Web.Resources.IsbnLanguagesStrings", typeof(IsbnLanguagesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string IsbnLanguage0 {
            get {
                return ResourceManager.GetString("IsbnLanguage0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string IsbnLanguage1 {
            get {
                return ResourceManager.GetString("IsbnLanguage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string IsbnLanguage2 {
            get {
                return ResourceManager.GetString("IsbnLanguage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string IsbnLanguage3 {
            get {
                return ResourceManager.GetString("IsbnLanguage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string IsbnLanguage4 {
            get {
                return ResourceManager.GetString("IsbnLanguage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string IsbnLanguage5 {
            get {
                return ResourceManager.GetString("IsbnLanguage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string IsbnLanguage7 {
            get {
                return ResourceManager.GetString("IsbnLanguage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string IsbnLanguage80 {
            get {
                return ResourceManager.GetString("IsbnLanguage80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian.
        /// </summary>
        public static string IsbnLanguage81 {
            get {
                return ResourceManager.GetString("IsbnLanguage81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string IsbnLanguage82 {
            get {
                return ResourceManager.GetString("IsbnLanguage82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string IsbnLanguage83 {
            get {
                return ResourceManager.GetString("IsbnLanguage83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string IsbnLanguage84 {
            get {
                return ResourceManager.GetString("IsbnLanguage84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian.
        /// </summary>
        public static string IsbnLanguage85 {
            get {
                return ResourceManager.GetString("IsbnLanguage85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string IsbnLanguage86 {
            get {
                return ResourceManager.GetString("IsbnLanguage86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string IsbnLanguage87 {
            get {
                return ResourceManager.GetString("IsbnLanguage87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string IsbnLanguage88 {
            get {
                return ResourceManager.GetString("IsbnLanguage88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string IsbnLanguage89 {
            get {
                return ResourceManager.GetString("IsbnLanguage89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string IsbnLanguage90 {
            get {
                return ResourceManager.GetString("IsbnLanguage90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string IsbnLanguage91 {
            get {
                return ResourceManager.GetString("IsbnLanguage91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        public static string IsbnLanguage92 {
            get {
                return ResourceManager.GetString("IsbnLanguage92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian.
        /// </summary>
        public static string IsbnLanguage93 {
            get {
                return ResourceManager.GetString("IsbnLanguage93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string IsbnLanguage94 {
            get {
                return ResourceManager.GetString("IsbnLanguage94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (ISBN Group {1}).
        /// </summary>
        public static string IsbnLanguageForAdminsFormat {
            get {
                return ResourceManager.GetString("IsbnLanguageForAdminsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string IsbnLanguageUnknown {
            get {
                return ResourceManager.GetString("IsbnLanguageUnknown", resourceCulture);
            }
        }
    }
}
