//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Iso639LanguagesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Iso639LanguagesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bieb.Web.Resources.Iso639LanguagesStrings", typeof(Iso639LanguagesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikaans.
        /// </summary>
        public static string Iso639Language_af {
            get {
                return ResourceManager.GetString("Iso639Language_af", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Iso639Language_ar {
            get {
                return ResourceManager.GetString("Iso639Language_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string Iso639Language_bg {
            get {
                return ResourceManager.GetString("Iso639Language_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengali.
        /// </summary>
        public static string Iso639Language_bn {
            get {
                return ResourceManager.GetString("Iso639Language_bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnian.
        /// </summary>
        public static string Iso639Language_bs {
            get {
                return ResourceManager.GetString("Iso639Language_bs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string Iso639Language_ca {
            get {
                return ResourceManager.GetString("Iso639Language_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Iso639Language_cs {
            get {
                return ResourceManager.GetString("Iso639Language_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Iso639Language_da {
            get {
                return ResourceManager.GetString("Iso639Language_da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Iso639Language_de {
            get {
                return ResourceManager.GetString("Iso639Language_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Iso639Language_el {
            get {
                return ResourceManager.GetString("Iso639Language_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Iso639Language_en {
            get {
                return ResourceManager.GetString("Iso639Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Iso639Language_es {
            get {
                return ResourceManager.GetString("Iso639Language_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string Iso639Language_et {
            get {
                return ResourceManager.GetString("Iso639Language_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Iso639Language_fa {
            get {
                return ResourceManager.GetString("Iso639Language_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Iso639Language_fi {
            get {
                return ResourceManager.GetString("Iso639Language_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Iso639Language_fr {
            get {
                return ResourceManager.GetString("Iso639Language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string Iso639Language_ga {
            get {
                return ResourceManager.GetString("Iso639Language_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaelic.
        /// </summary>
        public static string Iso639Language_gd {
            get {
                return ResourceManager.GetString("Iso639Language_gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string Iso639Language_he {
            get {
                return ResourceManager.GetString("Iso639Language_he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Iso639Language_hi {
            get {
                return ResourceManager.GetString("Iso639Language_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Iso639Language_hr {
            get {
                return ResourceManager.GetString("Iso639Language_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string Iso639Language_hu {
            get {
                return ResourceManager.GetString("Iso639Language_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string Iso639Language_id {
            get {
                return ResourceManager.GetString("Iso639Language_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        public static string Iso639Language_is {
            get {
                return ResourceManager.GetString("Iso639Language_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Iso639Language_it {
            get {
                return ResourceManager.GetString("Iso639Language_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Iso639Language_ja {
            get {
                return ResourceManager.GetString("Iso639Language_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javanese.
        /// </summary>
        public static string Iso639Language_jv {
            get {
                return ResourceManager.GetString("Iso639Language_jv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string Iso639Language_ka {
            get {
                return ResourceManager.GetString("Iso639Language_ka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Iso639Language_ko {
            get {
                return ResourceManager.GetString("Iso639Language_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurdish.
        /// </summary>
        public static string Iso639Language_ku {
            get {
                return ResourceManager.GetString("Iso639Language_ku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string Iso639Language_lt {
            get {
                return ResourceManager.GetString("Iso639Language_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string Iso639Language_lv {
            get {
                return ResourceManager.GetString("Iso639Language_lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian.
        /// </summary>
        public static string Iso639Language_mk {
            get {
                return ResourceManager.GetString("Iso639Language_mk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathi.
        /// </summary>
        public static string Iso639Language_mr {
            get {
                return ResourceManager.GetString("Iso639Language_mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay.
        /// </summary>
        public static string Iso639Language_ms {
            get {
                return ResourceManager.GetString("Iso639Language_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burmese.
        /// </summary>
        public static string Iso639Language_my {
            get {
                return ResourceManager.GetString("Iso639Language_my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Iso639Language_nl {
            get {
                return ResourceManager.GetString("Iso639Language_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string Iso639Language_no {
            get {
                return ResourceManager.GetString("Iso639Language_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punjabi.
        /// </summary>
        public static string Iso639Language_pa {
            get {
                return ResourceManager.GetString("Iso639Language_pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Iso639Language_pl {
            get {
                return ResourceManager.GetString("Iso639Language_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Iso639Language_pt {
            get {
                return ResourceManager.GetString("Iso639Language_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Iso639Language_ro {
            get {
                return ResourceManager.GetString("Iso639Language_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Iso639Language_ru {
            get {
                return ResourceManager.GetString("Iso639Language_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanskrit.
        /// </summary>
        public static string Iso639Language_sa {
            get {
                return ResourceManager.GetString("Iso639Language_sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string Iso639Language_sk {
            get {
                return ResourceManager.GetString("Iso639Language_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovene.
        /// </summary>
        public static string Iso639Language_sl {
            get {
                return ResourceManager.GetString("Iso639Language_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Iso639Language_sr {
            get {
                return ResourceManager.GetString("Iso639Language_sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Iso639Language_sv {
            get {
                return ResourceManager.GetString("Iso639Language_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        public static string Iso639Language_ta {
            get {
                return ResourceManager.GetString("Iso639Language_ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu.
        /// </summary>
        public static string Iso639Language_te {
            get {
                return ResourceManager.GetString("Iso639Language_te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Iso639Language_th {
            get {
                return ResourceManager.GetString("Iso639Language_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Iso639Language_tr {
            get {
                return ResourceManager.GetString("Iso639Language_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Iso639Language_uk {
            get {
                return ResourceManager.GetString("Iso639Language_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        public static string Iso639Language_ur {
            get {
                return ResourceManager.GetString("Iso639Language_ur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        public static string Iso639Language_uz {
            get {
                return ResourceManager.GetString("Iso639Language_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Iso639Language_vi {
            get {
                return ResourceManager.GetString("Iso639Language_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Iso639Language_zh {
            get {
                return ResourceManager.GetString("Iso639Language_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string Iso639LanguageForAdminsFormat {
            get {
                return ResourceManager.GetString("Iso639LanguageForAdminsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Iso639LanguageUnknown {
            get {
                return ResourceManager.GetString("Iso639LanguageUnknown", resourceCulture);
            }
        }
    }
}
