//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeopleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeopleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bieb.Web.Resources.PeopleStrings", typeof(PeopleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authored.
        /// </summary>
        public static string AuthoredBooks {
            get {
                return ResourceManager.GetString("AuthoredBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authored.
        /// </summary>
        public static string AuthoredStories {
            get {
                return ResourceManager.GetString("AuthoredStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born At.
        /// </summary>
        public static string BornAt {
            get {
                return ResourceManager.GetString("BornAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York.
        /// </summary>
        public static string BornAtPlaceholder {
            get {
                return ResourceManager.GetString("BornAtPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born On.
        /// </summary>
        public static string BornOn {
            get {
                return ResourceManager.GetString("BornOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string DayPlaceholder {
            get {
                return ResourceManager.GetString("DayPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died At.
        /// </summary>
        public static string DiedAt {
            get {
                return ResourceManager.GetString("DiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        public static string DiedAtPlaceholder {
            get {
                return ResourceManager.GetString("DiedAtPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died On.
        /// </summary>
        public static string DiedOn {
            get {
                return ResourceManager.GetString("DiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        public static string EditedBooks {
            get {
                return ResourceManager.GetString("EditedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find this person on.
        /// </summary>
        public static string FindPersonOn {
            get {
                return ResourceManager.GetString("FindPersonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augusto.
        /// </summary>
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female..
        /// </summary>
        public static string GenderTooltipFemale {
            get {
                return ResourceManager.GetString("GenderTooltipFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male..
        /// </summary>
        public static string GenderTooltipMale {
            get {
                return ResourceManager.GetString("GenderTooltipMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No explicit gender, e.g. this &quot;person&quot; represents multiple actual people..
        /// </summary>
        public static string GenderTooltipNone {
            get {
                return ResourceManager.GetString("GenderTooltipNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender of this person is not known..
        /// </summary>
        public static string GenderTooltipUnknown {
            get {
                return ResourceManager.GetString("GenderTooltipUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are all the authors, editors, and translators from books in my collection..
        /// </summary>
        public static string IndexIntroduction {
            get {
                return ResourceManager.GetString("IndexIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string MonthPlaceholder {
            get {
                return ResourceManager.GetString("MonthPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameGroupLabel {
            get {
                return ResourceManager.GetString("NameGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string NationalityHeader {
            get {
                return ResourceManager.GetString("NationalityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us, gb, nl, etc..
        /// </summary>
        public static string NationalityPlaceholder {
            get {
                return ResourceManager.GetString("NationalityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody..
        /// </summary>
        public static string NobodyBornToday {
            get {
                return ResourceManager.GetString("NobodyBornToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I see nobody on the road.&quot; said Alice. &quot;I only wish I had such eyes,&quot; the King remarked in a fretful tone. &quot;To be able to see Nobody!&quot;.
        /// </summary>
        public static string NobodyQuote {
            get {
                return ResourceManager.GetString("NobodyQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portrait.
        /// </summary>
        public static string PortraitAlt {
            get {
                return ResourceManager.GetString("PortraitAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von.
        /// </summary>
        public static string PrefixPlaceholder {
            get {
                return ResourceManager.GetString("PrefixPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have additional information about this person? Please let me know!.
        /// </summary>
        public static string RequestForAdditionalInfo {
            get {
                return ResourceManager.GetString("RequestForAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string ReviewText {
            get {
                return ResourceManager.GetString("ReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something interesting about this person; your opinion, an anecdote, etc..
        /// </summary>
        public static string ReviewTextPlaceholder {
            get {
                return ResourceManager.GetString("ReviewTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesHeader {
            get {
                return ResourceManager.GetString("RolesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graffenwald.
        /// </summary>
        public static string SurnamePlaceholder {
            get {
                return ResourceManager.GetString("SurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr..
        /// </summary>
        public static string TitlePlaceholder {
            get {
                return ResourceManager.GetString("TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated.
        /// </summary>
        public static string TranslatedBooks {
            get {
                return ResourceManager.GetString("TranslatedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated.
        /// </summary>
        public static string TranslatedStories {
            get {
                return ResourceManager.GetString("TranslatedStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.
        /// </summary>
        public static string YearPlaceholder {
            get {
                return ResourceManager.GetString("YearPlaceholder", resourceCulture);
            }
        }
    }
}
