//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiebResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeopleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeopleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bieb.Web.Resources.Views.People.PeopleStrings", typeof(PeopleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authored Collections.
        /// </summary>
        public static string AuthoredCollections {
            get {
                return ResourceManager.GetString("AuthoredCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authored Short Stories.
        /// </summary>
        public static string AuthoredShortStories {
            get {
                return ResourceManager.GetString("AuthoredShortStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born at.
        /// </summary>
        public static string BornAt {
            get {
                return ResourceManager.GetString("BornAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born.
        /// </summary>
        public static string BornOn {
            get {
                return ResourceManager.GetString("BornOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died at.
        /// </summary>
        public static string DiedAt {
            get {
                return ResourceManager.GetString("DiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died.
        /// </summary>
        public static string DiedOn {
            get {
                return ResourceManager.GetString("DiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited Books.
        /// </summary>
        public static string EditedBooks {
            get {
                return ResourceManager.GetString("EditedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find this person on.
        /// </summary>
        public static string FindPersonOn {
            get {
                return ResourceManager.GetString("FindPersonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderHeader {
            get {
                return ResourceManager.GetString("GenderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are all the authors, editors, and translators from books in my collection..
        /// </summary>
        public static string IndexIntroduction {
            get {
                return ResourceManager.GetString("IndexIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string NationalityHeader {
            get {
                return ResourceManager.GetString("NationalityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody..
        /// </summary>
        public static string NobodyBornToday {
            get {
                return ResourceManager.GetString("NobodyBornToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I see nobody on the road.&quot; said Alice. &quot;I only wish I had such eyes,&quot; the King remarked in a fretful tone. &quot;To be able to see Nobody!&quot;.
        /// </summary>
        public static string NobodyQuote {
            get {
                return ResourceManager.GetString("NobodyQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portrait.
        /// </summary>
        public static string PortraitAlt {
            get {
                return ResourceManager.GetString("PortraitAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have additional information about this person? Please let me know!.
        /// </summary>
        public static string RequestForAdditionalInfo {
            get {
                return ResourceManager.GetString("RequestForAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesHeader {
            get {
                return ResourceManager.GetString("RolesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Novels.
        /// </summary>
        public static string TranslatedNovels {
            get {
                return ResourceManager.GetString("TranslatedNovels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Short Stories.
        /// </summary>
        public static string TranslatedShortStories {
            get {
                return ResourceManager.GetString("TranslatedShortStories", resourceCulture);
            }
        }
    }
}
